name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller pandas openpyxl
      - name: Build exe
        run: |
          pyinstaller --onefile excel_modifier.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-modifier-exe
          path: dist/excel_modifier.exe
